# Generated by Django 4.0.4 on 2022-05-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('isStaff', models.BooleanField(default=False)),
                ('isWorking', models.BooleanField(default=False)),
            ],
        ),
    ]
