# Generated by Django 4.0.4 on 2022-06-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=240, verbose_name='staff_name')),
                ('password', models.CharField(max_length=240, verbose_name='password')),
                ('authToken', models.TextField(blank=True, null=True)),
                ('isLoggedIn', models.CharField(default='False', max_length=240)),
            ],
        ),
    ]
