# Generated by Django 4.0.4 on 2022-05-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240, verbose_name='name')),
                ('password', models.CharField(max_length=240, verbose_name='password')),
                ('authToken', models.TextField()),
                ('isLoggedIn', models.BooleanField(default=False)),
            ],
        ),
    ]
