# Generated by Django 4.0.4 on 2022-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_staff_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='authToken',
            field=models.TextField(null=True),
        ),
    ]
