# Generated by Django 4.0.4 on 2022-05-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_alter_staff_authtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='staff_name',
        ),
        migrations.AlterField(
            model_name='staff',
            name='authToken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='isLoggedIn',
            field=models.CharField(default='False', max_length=240),
        ),
    ]
