# Generated by Django 4.0.4 on 2022-05-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_rename_name_staff_staff_name_alter_staff_authtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_name',
            field=models.CharField(max_length=240, verbose_name='staff_name'),
        ),
    ]
